inherits = "noctis"

'ui.bufferline' = { fg = "white", bg = "dark-green", modifiers = ["underlined"] }
'ui.bufferline.active' = { fg = "light-green", bg = "mid-green", modifiers = ["italic"] }

'ui.window' = { fg = "white" }

"ui.popup" = { bg = "mid-green", fg = "light-orange" }
"ui.popup.info" = { bg = "mid-green", fg = "light-orange" }
